name: workflow name

on:
  pull_request:
    branches:
      - 'master'

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Use Node 14.x
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'
      - name: Install dependencies
        run: npm install
      - name: Build
        run: npm run build:ci
      - name: Test
        run: npm run test-headless